// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: SmartBand

#include "../ui.h"

// COMPONENT Calendar

lv_obj_t * ui_Calendar_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Calendar;
    cui_Calendar = lv_calendar_create(comp_parent);
    lv_calendar_set_today_date(cui_Calendar, 2024, 4, 15);
    lv_calendar_set_showed_date(cui_Calendar, 2024, 4);
    lv_obj_t * cui_Calendar_header = lv_calendar_header_arrow_create(cui_Calendar);
    lv_obj_set_width(cui_Calendar, 200);
    lv_obj_set_height(cui_Calendar, 240);
    lv_obj_set_align(cui_Calendar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(cui_Calendar, lv_color_hex(0x393C41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Calendar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_Calendar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_Calendar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_CALENDAR_NUM);
    children[UI_COMP_CALENDAR_CALENDAR] = cui_Calendar;
    lv_obj_add_event_cb(cui_Calendar, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Calendar, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Calendar_create_hook(cui_Calendar);
    return cui_Calendar;
}

