// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: SmartBand

#ifndef _UI_COMP_CALENDAR_H
#define _UI_COMP_CALENDAR_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Calendar
#define UI_COMP_CALENDAR_CALENDAR 0
#define _UI_COMP_CALENDAR_NUM 1
lv_obj_t * ui_Calendar_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
