// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: SmartBand

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Home
void ui_Home_screen_init(void);
void ui_event_Home(lv_event_t * e);
lv_obj_t * ui_Home;
lv_obj_t * ui_Home_Date;
lv_obj_t * ui_Home_Mouth;
lv_obj_t * ui_Home_TimeMinute;
lv_obj_t * ui_Home_TimeSplit;
lv_obj_t * ui_Home_TimeSecond;
void ui_event_Home_PanelApplication(lv_event_t * e);
lv_obj_t * ui_Home_PanelApplication;
lv_obj_t * ui_Home_LabelApplication;
lv_obj_t * ui_Home_ImageWeather;
lv_obj_t * ui_Home_LabelWeather;
lv_obj_t * ui_Home_ImageHeart;
lv_obj_t * ui_Home_LabelHeart;
lv_obj_t * ui_Home_ArcBattery;
lv_obj_t * ui_Home_ImageBattery;
lv_obj_t * ui_Home_LabelBattery;
// CUSTOM VARIABLES

// SCREEN: ui_NotificationPanel
void ui_NotificationPanel_screen_init(void);
void ui_event_NotificationPanel(lv_event_t * e);
lv_obj_t * ui_NotificationPanel;
lv_obj_t * ui_NotificationPanel_Container;
lv_obj_t * ui_NotificationPanel_ButtonBluetooth;
lv_obj_t * ui_NotificationPanel_ImageBluetooth;
lv_obj_t * ui_NotificationPanel_ButtonFlash;
lv_obj_t * ui_NotificationPanel_ImageFlash;
void ui_event_NotificationPanel_ButtonSettings(lv_event_t * e);
lv_obj_t * ui_NotificationPanel_ButtonSettings;
lv_obj_t * ui_NotificationPanel_ImageSettings;
lv_obj_t * ui_NotificationPanel_ButtonAlarm;
lv_obj_t * ui_NotificationPanel_ImageAlarm;
lv_obj_t * ui_NotificationPanel_ButtonNoDisturb;
lv_obj_t * ui_NotificationPanel_ImageNoDisturb;
lv_obj_t * ui_NotificationPanel_ButtonSleep;
lv_obj_t * ui_NotificationPanel_ImageSleep;
lv_obj_t * ui_NotificationPanel_LabelInfo;
lv_obj_t * ui_NotificationPanel_ImageBand;
lv_obj_t * ui_NotificationPanel_Slider1;
// CUSTOM VARIABLES

// SCREEN: ui_Settings
void ui_Settings_screen_init(void);
void ui_event_Settings(lv_event_t * e);
lv_obj_t * ui_Settings;
lv_obj_t * ui_Settings_Container;
void ui_event_Settings_ContainerAbout(lv_event_t * e);
lv_obj_t * ui_Settings_ContainerAbout;
lv_obj_t * ui_Settings_ImageAbout;
lv_obj_t * ui_Settings_LabelAbout;
// CUSTOM VARIABLES

// SCREEN: ui_About
void ui_About_screen_init(void);
void ui_event_About(lv_event_t * e);
lv_obj_t * ui_About;
lv_obj_t * ui_About_ImageAuthor;
lv_obj_t * ui_About_LabelAuthor;
// CUSTOM VARIABLES

// SCREEN: ui_Application
void ui_Application_screen_init(void);
void ui_event_Application(lv_event_t * e);
lv_obj_t * ui_Application;
lv_obj_t * ui_Application_Container;
void ui_event_Application_ContainerCalendar(lv_event_t * e);
lv_obj_t * ui_Application_ContainerCalendar;
lv_obj_t * ui_Application_ImageCalendar;
lv_obj_t * ui_Application_LabelCalendar;
// CUSTOM VARIABLES

// SCREEN: ui_Calendar
void ui_Calendar_screen_init(void);
void ui_event_Calendar(lv_event_t * e);
lv_obj_t * ui_Calendar;
lv_obj_t * ui_Calendar_CalendarIns;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Home(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_NotificationPanel, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 300, 0, &ui_NotificationPanel_screen_init);
    }
}

void ui_event_Home_PanelApplication(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Application, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Application_screen_init);
    }
}

void ui_event_NotificationPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_Home_screen_init);
    }
}

void ui_event_NotificationPanel_ButtonSettings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Settings_screen_init);
    }
}

void ui_event_Settings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Home_screen_init);
    }
}

void ui_event_Settings_ContainerAbout(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_About, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_About_screen_init);
    }
}

void ui_event_About(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Settings_screen_init);
    }
}

void ui_event_Application(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Home_screen_init);
    }
}

void ui_event_Application_ContainerCalendar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Calendar, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Calendar_screen_init);
    }
}

void ui_event_Calendar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Application, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Application_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Home_screen_init();
    ui_NotificationPanel_screen_init();
    ui_Settings_screen_init();
    ui_About_screen_init();
    ui_Application_screen_init();
    ui_Calendar_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Home);
}
