// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: SmartBand

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Home
void ui_Home_screen_init(void);
void ui_event_Home(lv_event_t * e);
lv_obj_t * ui_Home;
lv_obj_t * ui_Home_Date;
lv_obj_t * ui_Home_Mouth;
lv_obj_t * ui_Home_TimeMinute;
lv_obj_t * ui_Home_TimeSplit;
lv_obj_t * ui_Home_TimeSecond;
lv_obj_t * ui_Home_ArcBattery;
lv_obj_t * ui_Home_LabelBattery;
lv_obj_t * ui_Home_ImageBattery;
lv_obj_t * ui_Home_ContainerInfo;
lv_obj_t * ui_Home_LabelTemp;
lv_obj_t * ui_Home_LabelWeather;
lv_obj_t * ui_Home_ImageWeather;
lv_obj_t * ui_Home_LabelHeartbeat;
lv_obj_t * ui_Home_ImageHeartbeat;
lv_obj_t * ui_Home_PanelInfo;
lv_obj_t * ui_Home_LabelStep;
// CUSTOM VARIABLES

// SCREEN: ui_NotificationPanel
void ui_NotificationPanel_screen_init(void);
void ui_event_NotificationPanel(lv_event_t * e);
lv_obj_t * ui_NotificationPanel;
lv_obj_t * ui_NotificationPanel_Container;
lv_obj_t * ui_NotificationPanel_ButtonBlueTooth;
lv_obj_t * ui_NotificationPanel_ImageBluetooth;
lv_obj_t * ui_NotificationPanel_ButtonLighting;
lv_obj_t * ui_NotificationPanel_ImageLighting;
void ui_event_NotificationPanel_ButtonSetting(lv_event_t * e);
lv_obj_t * ui_NotificationPanel_ButtonSetting;
lv_obj_t * ui_NotificationPanel_ImageSettings;
lv_obj_t * ui_NotificationPanel_ButtonAlarm;
lv_obj_t * ui_NotificationPanel_ImageAlarm;
lv_obj_t * ui_NotificationPanel_ButtonNoDisturb;
lv_obj_t * ui_NotificationPanel_ImageNoDisturb;
lv_obj_t * ui_NotificationPanel_ButtonSleep;
lv_obj_t * ui_NotificationPanel_ImageSleep;
lv_obj_t * ui_NotificationPanel_LabelInfo;
lv_obj_t * ui_NotificationPanel_ImageBand;
lv_obj_t * ui_NotificationPanel_Slider1;
// CUSTOM VARIABLES

// SCREEN: ui_Settings
void ui_Settings_screen_init(void);
void ui_event_Settings(lv_event_t * e);
lv_obj_t * ui_Settings;
lv_obj_t * ui_Settings_Container;
lv_obj_t * ui_Settings_Container1;
lv_obj_t * ui_Settings_Image1;
lv_obj_t * ui_Settings_Label1;
lv_obj_t * ui_Settings_Container2;
lv_obj_t * ui_Settings_Image3;
lv_obj_t * ui_Settings_Container3;
lv_obj_t * ui_Settings_Image2;
lv_obj_t * ui_Settings_Container4;
lv_obj_t * ui_Settings_Image4;
lv_obj_t * ui_Settings_Container5;
lv_obj_t * ui_Settings_Image5;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Home(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_NotificationPanel, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 300, 0, &ui_NotificationPanel_screen_init);
    }
}

void ui_event_NotificationPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_Home_screen_init);
    }
}

void ui_event_NotificationPanel_ButtonSetting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Settings_screen_init);
    }
}

void ui_event_Settings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Home_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Home_screen_init();
    ui_NotificationPanel_screen_init();
    ui_Settings_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Home);
}
