// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: SmartBand

#ifndef _SMARTBAND_UI_H
#define _SMARTBAND_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Home
void ui_Home_screen_init(void);
void ui_event_Home(lv_event_t * e);
extern lv_obj_t * ui_Home;
extern lv_obj_t * ui_Home_Date;
extern lv_obj_t * ui_Home_Mouth;
extern lv_obj_t * ui_Home_TimeMinute;
extern lv_obj_t * ui_Home_TimeSplit;
extern lv_obj_t * ui_Home_TimeSecond;
extern lv_obj_t * ui_Home_ArcBattery;
extern lv_obj_t * ui_Home_LabelBattery;
extern lv_obj_t * ui_Home_ImageBattery;
extern lv_obj_t * ui_Home_ContainerInfo;
extern lv_obj_t * ui_Home_LabelTemp;
extern lv_obj_t * ui_Home_LabelWeather;
extern lv_obj_t * ui_Home_ImageWeather;
extern lv_obj_t * ui_Home_LabelHeartbeat;
extern lv_obj_t * ui_Home_ImageHeartbeat;
extern lv_obj_t * ui_Home_PanelInfo;
extern lv_obj_t * ui_Home_LabelStep;
// CUSTOM VARIABLES

// SCREEN: ui_NotificationPanel
void ui_NotificationPanel_screen_init(void);
void ui_event_NotificationPanel(lv_event_t * e);
extern lv_obj_t * ui_NotificationPanel;
extern lv_obj_t * ui_NotificationPanel_Container;
extern lv_obj_t * ui_NotificationPanel_ButtonBlueTooth;
extern lv_obj_t * ui_NotificationPanel_ImageBluetooth;
extern lv_obj_t * ui_NotificationPanel_ButtonLighting;
extern lv_obj_t * ui_NotificationPanel_ImageLighting;
void ui_event_NotificationPanel_ButtonSetting(lv_event_t * e);
extern lv_obj_t * ui_NotificationPanel_ButtonSetting;
extern lv_obj_t * ui_NotificationPanel_ImageSettings;
extern lv_obj_t * ui_NotificationPanel_ButtonAlarm;
extern lv_obj_t * ui_NotificationPanel_ImageAlarm;
extern lv_obj_t * ui_NotificationPanel_ButtonNoDisturb;
extern lv_obj_t * ui_NotificationPanel_ImageNoDisturb;
extern lv_obj_t * ui_NotificationPanel_ButtonSleep;
extern lv_obj_t * ui_NotificationPanel_ImageSleep;
extern lv_obj_t * ui_NotificationPanel_LabelInfo;
extern lv_obj_t * ui_NotificationPanel_ImageBand;
extern lv_obj_t * ui_NotificationPanel_Slider1;
// CUSTOM VARIABLES

// SCREEN: ui_Settings
void ui_Settings_screen_init(void);
void ui_event_Settings(lv_event_t * e);
extern lv_obj_t * ui_Settings;
extern lv_obj_t * ui_Settings_Container;
extern lv_obj_t * ui_Settings_Container1;
extern lv_obj_t * ui_Settings_Image1;
extern lv_obj_t * ui_Settings_Label1;
extern lv_obj_t * ui_Settings_Container2;
extern lv_obj_t * ui_Settings_Image3;
extern lv_obj_t * ui_Settings_Container3;
extern lv_obj_t * ui_Settings_Image2;
extern lv_obj_t * ui_Settings_Container4;
extern lv_obj_t * ui_Settings_Image4;
extern lv_obj_t * ui_Settings_Container5;
extern lv_obj_t * ui_Settings_Image5;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_battery_png);    // assets/battery.png
LV_IMG_DECLARE(ui_img_weather_sunny_png);    // assets/weather_sunny.png
LV_IMG_DECLARE(ui_img_heartbeat_png);    // assets/heartbeat.png
LV_IMG_DECLARE(ui_img_bluetooth_png);    // assets/bluetooth.png
LV_IMG_DECLARE(ui_img_lighting_png);    // assets/lighting.png
LV_IMG_DECLARE(ui_img_settings_png);    // assets/settings.png
LV_IMG_DECLARE(ui_img_alarm_png);    // assets/alarm.png
LV_IMG_DECLARE(ui_img_no_disturb_png);    // assets/no_disturb.png
LV_IMG_DECLARE(ui_img_sleep_png);    // assets/sleep.png
LV_IMG_DECLARE(ui_img_band_png);    // assets/band.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
