// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: SmartBand

#ifndef _SMARTBAND_UI_H
#define _SMARTBAND_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Home
void ui_Home_screen_init(void);
void ui_event_Home(lv_event_t * e);
extern lv_obj_t * ui_Home;
extern lv_obj_t * ui_Home_Date;
extern lv_obj_t * ui_Home_Weekday;
extern lv_obj_t * ui_Home_TimeHour;
extern lv_obj_t * ui_Home_TimeSplit;
extern lv_obj_t * ui_Home_TimeMinute;
void ui_event_Home_PanelApplication(lv_event_t * e);
extern lv_obj_t * ui_Home_PanelApplication;
extern lv_obj_t * ui_Home_LabelApplication;
extern lv_obj_t * ui_Home_ImageWeather;
extern lv_obj_t * ui_Home_LabelWeather;
extern lv_obj_t * ui_Home_ImageHeart;
extern lv_obj_t * ui_Home_LabelHeart;
extern lv_obj_t * ui_Home_ArcBattery;
extern lv_obj_t * ui_Home_ImageBattery;
extern lv_obj_t * ui_Home_LabelBattery;
// CUSTOM VARIABLES

// SCREEN: ui_NotificationPanel
void ui_NotificationPanel_screen_init(void);
void ui_event_NotificationPanel(lv_event_t * e);
extern lv_obj_t * ui_NotificationPanel;
extern lv_obj_t * ui_NotificationPanel_Container;
extern lv_obj_t * ui_NotificationPanel_ButtonBluetooth;
extern lv_obj_t * ui_NotificationPanel_ImageBluetooth;
void ui_event_NotificationPanel_ButtonFlash(lv_event_t * e);
extern lv_obj_t * ui_NotificationPanel_ButtonFlash;
extern lv_obj_t * ui_NotificationPanel_ImageFlash;
void ui_event_NotificationPanel_ButtonSettings(lv_event_t * e);
extern lv_obj_t * ui_NotificationPanel_ButtonSettings;
extern lv_obj_t * ui_NotificationPanel_ImageSettings;
void ui_event_NotificationPanel_ButtonAlarm(lv_event_t * e);
extern lv_obj_t * ui_NotificationPanel_ButtonAlarm;
extern lv_obj_t * ui_NotificationPanel_ImageAlarm;
extern lv_obj_t * ui_NotificationPanel_ButtonNoDisturb;
extern lv_obj_t * ui_NotificationPanel_ImageNoDisturb;
extern lv_obj_t * ui_NotificationPanel_ButtonSleep;
extern lv_obj_t * ui_NotificationPanel_ImageSleep;
extern lv_obj_t * ui_NotificationPanel_LabelInfo;
extern lv_obj_t * ui_NotificationPanel_ImageBand;
extern lv_obj_t * ui_NotificationPanel_SliderLight;
// CUSTOM VARIABLES

// SCREEN: ui_Settings
void ui_Settings_screen_init(void);
void ui_event_Settings(lv_event_t * e);
extern lv_obj_t * ui_Settings;
extern lv_obj_t * ui_Settings_Container;
void ui_event_Settings_ContainerDate(lv_event_t * e);
extern lv_obj_t * ui_Settings_ContainerDate;
extern lv_obj_t * ui_Settings_ImageDate;
extern lv_obj_t * ui_Settings_LabelDate;
void ui_event_Settings_ContainerTime(lv_event_t * e);
extern lv_obj_t * ui_Settings_ContainerTime;
extern lv_obj_t * ui_Settings_ImageTime;
extern lv_obj_t * ui_Settings_LabelTime;
void ui_event_Settings_ContainerBluetoth(lv_event_t * e);
extern lv_obj_t * ui_Settings_ContainerBluetoth;
extern lv_obj_t * ui_Settings_ImageBluetooth;
extern lv_obj_t * ui_Settings_LabelBluetooth;
void ui_event_Settings_ContainerTurnOffTime(lv_event_t * e);
extern lv_obj_t * ui_Settings_ContainerTurnOffTime;
extern lv_obj_t * ui_Settings_ImageTurnOffTime;
extern lv_obj_t * ui_Settings_LabelTurnOffTime;
void ui_event_Settings_ContainerWristOn(lv_event_t * e);
extern lv_obj_t * ui_Settings_ContainerWristOn;
extern lv_obj_t * ui_Settings_ImageWristOn;
extern lv_obj_t * ui_Settings_LabelWristOn;
void ui_event_Settings_ContainerAbout(lv_event_t * e);
extern lv_obj_t * ui_Settings_ContainerAbout;
extern lv_obj_t * ui_Settings_ImageAbout;
extern lv_obj_t * ui_Settings_LabelAbout;
// CUSTOM VARIABLES

// SCREEN: ui_SettingsAbout
void ui_SettingsAbout_screen_init(void);
void ui_event_SettingsAbout(lv_event_t * e);
extern lv_obj_t * ui_SettingsAbout;
extern lv_obj_t * ui_SettingsAbout_ImageAuthor;
extern lv_obj_t * ui_SettingsAbout_LabelAuthor;
// CUSTOM VARIABLES

// SCREEN: ui_Application
void ui_Application_screen_init(void);
void ui_event_Application(lv_event_t * e);
extern lv_obj_t * ui_Application;
extern lv_obj_t * ui_Application_Container;
void ui_event_Application_ContainerAlarm(lv_event_t * e);
extern lv_obj_t * ui_Application_ContainerAlarm;
extern lv_obj_t * ui_Application_ImageAlarm;
extern lv_obj_t * ui_Application_LabelAlarm;
void ui_event_Application_ContainerCalendar(lv_event_t * e);
extern lv_obj_t * ui_Application_ContainerCalendar;
extern lv_obj_t * ui_Application_ImageCalendar;
extern lv_obj_t * ui_Application_LabelCalendar;
void ui_event_Application_ContainerTimer(lv_event_t * e);
extern lv_obj_t * ui_Application_ContainerTimer;
extern lv_obj_t * ui_Application_ImageTimer;
extern lv_obj_t * ui_Application_LabelTimer;
void ui_event_Application_ContainerHeartBeat(lv_event_t * e);
extern lv_obj_t * ui_Application_ContainerHeartBeat;
extern lv_obj_t * ui_Application_ImageHeartBeat;
extern lv_obj_t * ui_Application_LabelHeartBeat;
void ui_event_Application_ContainerFlash(lv_event_t * e);
extern lv_obj_t * ui_Application_ContainerFlash;
extern lv_obj_t * ui_Application_ImageFlash;
extern lv_obj_t * ui_Application_LabelFlash;
void ui_event_Application_ContainerThermomenter(lv_event_t * e);
extern lv_obj_t * ui_Application_ContainerThermomenter;
extern lv_obj_t * ui_Application_ImageThermomenter;
extern lv_obj_t * ui_Application_LabelThermomenter;
void ui_event_Application_ContainerDirector(lv_event_t * e);
extern lv_obj_t * ui_Application_ContainerDirector;
extern lv_obj_t * ui_Application_ImageDirector;
extern lv_obj_t * ui_Application_LabelDirector;
void ui_event_Application_ContainerSettings(lv_event_t * e);
extern lv_obj_t * ui_Application_ContainerSettings;
extern lv_obj_t * ui_Application_ImageSettings;
extern lv_obj_t * ui_Application_LabelSettings;
// CUSTOM VARIABLES

// SCREEN: ui_Timer
void ui_Timer_screen_init(void);
void ui_event_Timer(lv_event_t * e);
extern lv_obj_t * ui_Timer;
extern lv_obj_t * ui_Timer_ArcTimer;
extern lv_obj_t * ui_Timer_LabelTime;
extern lv_obj_t * ui_Timer_ButtonStart;
extern lv_obj_t * ui_Timer_ImageStart;
extern lv_obj_t * ui_Timer_ButtonRestart;
extern lv_obj_t * ui_Timer_ImageRestart;
// CUSTOM VARIABLES

// SCREEN: ui_SettingsWristOn
void ui_SettingsWristOn_screen_init(void);
void ui_event_SettingsWristOn(lv_event_t * e);
extern lv_obj_t * ui_SettingsWristOn;
extern lv_obj_t * ui_SettingsWristOn_ImageWristOn;
extern lv_obj_t * ui_SettingsWristOn_SwitchWristOn;
extern lv_obj_t * ui_SettingsWristOn_LabelWristOn;
extern lv_obj_t * ui_SettingsWristOn_LabelWristOnHint;
// CUSTOM VARIABLES

// SCREEN: ui_SettingsLockTime
void ui_SettingsLockTime_screen_init(void);
void ui_event_SettingsLockTime(lv_event_t * e);
extern lv_obj_t * ui_SettingsLockTime;
extern lv_obj_t * ui_SettingsLockTime_ImageLockTime;
extern lv_obj_t * ui_SettingsLockTime_LabelLockTime;
extern lv_obj_t * ui_SettingsLockTime_LabelLockTimeHint;
extern lv_obj_t * ui_SettingsLockTime_Dropdown;
// CUSTOM VARIABLES

// SCREEN: ui_SettingsBluetooth
void ui_SettingsBluetooth_screen_init(void);
void ui_event_SettingsBluetooth(lv_event_t * e);
extern lv_obj_t * ui_SettingsBluetooth;
extern lv_obj_t * ui_SettingsBluetooth_LabelBluetooth;
void ui_event_SettingsBluetooth_ImageBluetooth(lv_event_t * e);
extern lv_obj_t * ui_SettingsBluetooth_ImageBluetooth;
extern lv_obj_t * ui_SettingsBluetooth_SwitchBluetooth;
extern lv_obj_t * ui_SettingsBluetooth_LabelBluetoothHint;
// CUSTOM VARIABLES

// SCREEN: ui_SettingsDebug
void ui_SettingsDebug_screen_init(void);
void ui_event_SettingsDebug(lv_event_t * e);
extern lv_obj_t * ui_SettingsDebug;
extern lv_obj_t * ui_SettingsDebug_Keyboard;
extern lv_obj_t * ui_SettingsDebug_TextAreaRX;
extern lv_obj_t * ui_SettingsDebug_TextAreaTX;
extern lv_obj_t * ui_SettingsDebug_LabelTX;
extern lv_obj_t * ui_SettingsDebug_LabelRX;
// CUSTOM VARIABLES

// SCREEN: ui_SettingsTime
void ui_SettingsTime_screen_init(void);
void ui_event_SettingsTime(lv_event_t * e);
extern lv_obj_t * ui_SettingsTime;
extern lv_obj_t * ui_SettingsTime_ImageSetTime;
extern lv_obj_t * ui_SettingsTime_LabelSetTime;
extern lv_obj_t * ui_SettingsTime_LabelSetTimeHint;
extern lv_obj_t * ui_SettingsTime_ButtonSync;
extern lv_obj_t * ui_SettingsTime_LabelSync;
// CUSTOM VARIABLES

// SCREEN: ui_SettingsDate
void ui_SettingsDate_screen_init(void);
void ui_event_SettingsDate(lv_event_t * e);
extern lv_obj_t * ui_SettingsDate;
extern lv_obj_t * ui_SettingsDate_ImageSetDate;
extern lv_obj_t * ui_SettingsDate_LabelSetDate;
extern lv_obj_t * ui_SettingsDate_LabelSetDateHint;
extern lv_obj_t * ui_SettingsDate_ButtonSync;
extern lv_obj_t * ui_SettingsDate_LabelSync;
// CUSTOM VARIABLES

// SCREEN: ui_Thermometer
void ui_Thermometer_screen_init(void);
void ui_event_Thermometer(lv_event_t * e);
extern lv_obj_t * ui_Thermometer;
extern lv_obj_t * ui_Thermometer_LabelThermometer;
extern lv_obj_t * ui_Thermometer_ImageTemp;
extern lv_obj_t * ui_Thermometer_ImageHumi;
extern lv_obj_t * ui_Thermometer_LabelTemp;
extern lv_obj_t * ui_Thermometer_LabelHumi;
extern lv_obj_t * ui_Thermometer_ButtonFresh;
extern lv_obj_t * ui_Thermometer_ImageFresh;
// CUSTOM VARIABLES

// SCREEN: ui_HeartBeat
void ui_HeartBeat_screen_init(void);
void ui_event_HeartBeat(lv_event_t * e);
extern lv_obj_t * ui_HeartBeat;
extern lv_obj_t * ui_HeartBeat_LabelHeartbeat;
extern lv_obj_t * ui_HeartBeat_ImageHeartBeat;
extern lv_obj_t * ui_HeartBeat_LabelHeartbeatNum;
extern lv_obj_t * ui_HeartBeat_ButtonFresh;
extern lv_obj_t * ui_HeartBeat_ImageFresh;
// CUSTOM VARIABLES

// SCREEN: ui_Director
void ui_Director_screen_init(void);
void ui_event_Director(lv_event_t * e);
extern lv_obj_t * ui_Director;
extern lv_obj_t * ui_Director_LabelDirector;
extern lv_obj_t * ui_Director_ImageCompass;
extern lv_obj_t * ui_Director_LabelCompass;
extern lv_obj_t * ui_Director_ImageHeight;
extern lv_obj_t * ui_Director_LabelHeight;
extern lv_obj_t * ui_Director_ButtonFresh;
extern lv_obj_t * ui_Director_ImageFresh;
// CUSTOM VARIABLES

// SCREEN: ui_Flash
void ui_Flash_screen_init(void);
void ui_event_Flash(lv_event_t * e);
extern lv_obj_t * ui_Flash;
// CUSTOM VARIABLES

// SCREEN: ui_Alarm
void ui_Alarm_screen_init(void);
void ui_event_Alarm(lv_event_t * e);
extern lv_obj_t * ui_Alarm;
extern lv_obj_t * ui_Alarm_LabelAlarm;
extern lv_obj_t * ui_Alarm_ImageAlarm;
void ui_event_Alarm_ButtonBack(lv_event_t * e);
extern lv_obj_t * ui_Alarm_ButtonBack;
extern lv_obj_t * ui_Alarm_LabelBack;
extern lv_obj_t * ui_Alarm_LabelAlarmInfo;
// CUSTOM VARIABLES

// SCREEN: ui_Calendar
void ui_Calendar_screen_init(void);
void ui_event_Calendar(lv_event_t * e);
extern lv_obj_t * ui_Calendar;
extern lv_obj_t * ui_Calendar_CalendarInstance;
// CUSTOM VARIABLES

// EVENTS

void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_weather_sunny_png);    // assets/weather_sunny.png
LV_IMG_DECLARE(ui_img_heartbeat_png);    // assets/heartbeat.png
LV_IMG_DECLARE(ui_img_battery_png);    // assets/battery.png
LV_IMG_DECLARE(ui_img_bluetooth_png);    // assets/bluetooth.png
LV_IMG_DECLARE(ui_img_lighting_png);    // assets/lighting.png
LV_IMG_DECLARE(ui_img_settings_png);    // assets/settings.png
LV_IMG_DECLARE(ui_img_alarm_png);    // assets/alarm.png
LV_IMG_DECLARE(ui_img_no_disturb_png);    // assets/no_disturb.png
LV_IMG_DECLARE(ui_img_sleep_png);    // assets/sleep.png
LV_IMG_DECLARE(ui_img_band_png);    // assets/band.png
LV_IMG_DECLARE(ui_img_calendar_png);    // assets/calendar.png
LV_IMG_DECLARE(ui_img_time_png);    // assets/time.png
LV_IMG_DECLARE(ui_img_turn_off_time_png);    // assets/turn_off_time.png
LV_IMG_DECLARE(ui_img_wrist_on_png);    // assets/wrist_on.png
LV_IMG_DECLARE(ui_img_author_png);    // assets/author.png
LV_IMG_DECLARE(ui_img_timer_png);    // assets/timer.png
LV_IMG_DECLARE(ui_img_thermometer_png);    // assets/thermometer.png
LV_IMG_DECLARE(ui_img_director_png);    // assets/director.png
LV_IMG_DECLARE(ui_img_start_png);    // assets/start.png
LV_IMG_DECLARE(ui_img_restart_png);    // assets/restart.png
LV_IMG_DECLARE(ui_img_humi_png);    // assets/humi.png
LV_IMG_DECLARE(ui_img_height_png);    // assets/height.png

// FONTS
LV_FONT_DECLARE(ui_font_Font);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
