// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: SmartBand

#ifndef _SMARTBAND_UI_H
#define _SMARTBAND_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Home
void ui_Home_screen_init(void);
void ui_event_Home(lv_event_t * e);
extern lv_obj_t * ui_Home;
extern lv_obj_t * ui_Home_Date;
extern lv_obj_t * ui_Home_Mouth;
extern lv_obj_t * ui_Home_TimeMinute;
extern lv_obj_t * ui_Home_TimeSplit;
extern lv_obj_t * ui_Home_TimeSecond;
void ui_event_Home_PanelApplication(lv_event_t * e);
extern lv_obj_t * ui_Home_PanelApplication;
extern lv_obj_t * ui_Home_LabelApplication;
extern lv_obj_t * ui_Home_ImageWeather;
extern lv_obj_t * ui_Home_LabelWeather;
extern lv_obj_t * ui_Home_ImageHeart;
extern lv_obj_t * ui_Home_LabelHeart;
extern lv_obj_t * ui_Home_ArcBattery;
extern lv_obj_t * ui_Home_ImageBattery;
extern lv_obj_t * ui_Home_LabelBattery;
// CUSTOM VARIABLES

// SCREEN: ui_NotificationPanel
void ui_NotificationPanel_screen_init(void);
void ui_event_NotificationPanel(lv_event_t * e);
extern lv_obj_t * ui_NotificationPanel;
extern lv_obj_t * ui_NotificationPanel_Container;
extern lv_obj_t * ui_NotificationPanel_ButtonBluetooth;
extern lv_obj_t * ui_NotificationPanel_ImageBluetooth;
extern lv_obj_t * ui_NotificationPanel_ButtonFlash;
extern lv_obj_t * ui_NotificationPanel_ImageFlash;
void ui_event_NotificationPanel_ButtonSettings(lv_event_t * e);
extern lv_obj_t * ui_NotificationPanel_ButtonSettings;
extern lv_obj_t * ui_NotificationPanel_ImageSettings;
extern lv_obj_t * ui_NotificationPanel_ButtonAlarm;
extern lv_obj_t * ui_NotificationPanel_ImageAlarm;
extern lv_obj_t * ui_NotificationPanel_ButtonNoDisturb;
extern lv_obj_t * ui_NotificationPanel_ImageNoDisturb;
extern lv_obj_t * ui_NotificationPanel_ButtonSleep;
extern lv_obj_t * ui_NotificationPanel_ImageSleep;
extern lv_obj_t * ui_NotificationPanel_LabelInfo;
extern lv_obj_t * ui_NotificationPanel_ImageBand;
extern lv_obj_t * ui_NotificationPanel_Slider1;
// CUSTOM VARIABLES

// SCREEN: ui_Settings
void ui_Settings_screen_init(void);
void ui_event_Settings(lv_event_t * e);
extern lv_obj_t * ui_Settings;
extern lv_obj_t * ui_Settings_Container;
void ui_event_Settings_ContainerAbout(lv_event_t * e);
extern lv_obj_t * ui_Settings_ContainerAbout;
extern lv_obj_t * ui_Settings_ImageAbout;
extern lv_obj_t * ui_Settings_LabelAbout;
// CUSTOM VARIABLES

// SCREEN: ui_About
void ui_About_screen_init(void);
void ui_event_About(lv_event_t * e);
extern lv_obj_t * ui_About;
extern lv_obj_t * ui_About_ImageAuthor;
extern lv_obj_t * ui_About_LabelAuthor;
// CUSTOM VARIABLES

// SCREEN: ui_Application
void ui_Application_screen_init(void);
void ui_event_Application(lv_event_t * e);
extern lv_obj_t * ui_Application;
extern lv_obj_t * ui_Application_Container;
void ui_event_Application_ContainerCalendar(lv_event_t * e);
extern lv_obj_t * ui_Application_ContainerCalendar;
extern lv_obj_t * ui_Application_ImageCalendar;
extern lv_obj_t * ui_Application_LabelCalendar;
// CUSTOM VARIABLES

// SCREEN: ui_Calendar
void ui_Calendar_screen_init(void);
void ui_event_Calendar(lv_event_t * e);
extern lv_obj_t * ui_Calendar;
extern lv_obj_t * ui_Calendar_CalendarIns;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_weather_sunny_png);    // assets/weather_sunny.png
LV_IMG_DECLARE(ui_img_heartbeat_png);    // assets/heartbeat.png
LV_IMG_DECLARE(ui_img_battery_png);    // assets/battery.png
LV_IMG_DECLARE(ui_img_bluetooth_png);    // assets/bluetooth.png
LV_IMG_DECLARE(ui_img_lighting_png);    // assets/lighting.png
LV_IMG_DECLARE(ui_img_settings_png);    // assets/settings.png
LV_IMG_DECLARE(ui_img_alarm_png);    // assets/alarm.png
LV_IMG_DECLARE(ui_img_no_disturb_png);    // assets/no_disturb.png
LV_IMG_DECLARE(ui_img_sleep_png);    // assets/sleep.png
LV_IMG_DECLARE(ui_img_band_png);    // assets/band.png
LV_IMG_DECLARE(ui_img_author_png);    // assets/author.png
LV_IMG_DECLARE(ui_img_calendar_png);    // assets/calendar.png

// FONTS
LV_FONT_DECLARE(ui_font_Font);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
