// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: SmartBand

#include "ui.h"

#include "ui/func/ui_timer.h"

void ui_init_action(lv_event_t *e) { ui_timer_init(); }
