// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: SmartBand

#include "../ui.h"

void ui_Home_screen_init(void)
{
    ui_Home = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Home, lv_color_hex(0x222831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Home, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Home_Date = lv_label_create(ui_Home);
    lv_obj_set_width(ui_Home_Date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Home_Date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Home_Date, 5);
    lv_obj_set_y(ui_Home_Date, -95);
    lv_obj_set_align(ui_Home_Date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Home_Date, "04-15");
    lv_obj_set_style_text_color(ui_Home_Date, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Home_Date, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Home_Date, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Home_Mouth = lv_label_create(ui_Home);
    lv_obj_set_width(ui_Home_Mouth, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Home_Mouth, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Home_Mouth, -70);
    lv_obj_set_y(ui_Home_Mouth, -95);
    lv_obj_set_align(ui_Home_Mouth, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Home_Mouth, "Tue");
    lv_obj_set_style_text_color(ui_Home_Mouth, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Home_Mouth, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Home_Mouth, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Home_TimeMinute = lv_label_create(ui_Home);
    lv_obj_set_width(ui_Home_TimeMinute, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Home_TimeMinute, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Home_TimeMinute, -70);
    lv_obj_set_y(ui_Home_TimeMinute, -60);
    lv_obj_set_align(ui_Home_TimeMinute, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Home_TimeMinute, "12");
    lv_obj_set_style_text_color(ui_Home_TimeMinute, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Home_TimeMinute, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Home_TimeMinute, &ui_font_FontMontserrat, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Home_TimeSecond = lv_label_create(ui_Home);
    lv_obj_set_width(ui_Home_TimeSecond, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Home_TimeSecond, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Home_TimeSecond, 10);
    lv_obj_set_y(ui_Home_TimeSecond, -60);
    lv_obj_set_align(ui_Home_TimeSecond, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Home_TimeSecond, "34");
    lv_obj_set_style_text_color(ui_Home_TimeSecond, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Home_TimeSecond, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Home_TimeSecond, &ui_font_FontMontserrat, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Home_ArcBattery = lv_arc_create(ui_Home);
    lv_obj_set_width(ui_Home_ArcBattery, 66);
    lv_obj_set_height(ui_Home_ArcBattery, 68);
    lv_obj_set_x(ui_Home_ArcBattery, 78);
    lv_obj_set_y(ui_Home_ArcBattery, -70);
    lv_obj_set_align(ui_Home_ArcBattery, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Home_ArcBattery, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_Home_ArcBattery, 50);
    lv_obj_set_style_arc_color(ui_Home_ArcBattery, lv_color_hex(0xBCBCBC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Home_ArcBattery, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Home_ArcBattery, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Home_ArcBattery, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_opa(ui_Home_ArcBattery, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Home_LabelBattery = lv_label_create(ui_Home_ArcBattery);
    lv_obj_set_width(ui_Home_LabelBattery, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Home_LabelBattery, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Home_LabelBattery, -2);
    lv_obj_set_y(ui_Home_LabelBattery, -1);
    lv_obj_set_align(ui_Home_LabelBattery, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Home_LabelBattery, "50%");
    lv_obj_set_style_text_color(ui_Home_LabelBattery, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Home_LabelBattery, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Home_ImageBattery = lv_image_create(ui_Home_ArcBattery);
    lv_image_set_src(ui_Home_ImageBattery, &ui_img_battery_png);
    lv_obj_set_width(ui_Home_ImageBattery, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Home_ImageBattery, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Home_ImageBattery, 0);
    lv_obj_set_y(ui_Home_ImageBattery, 20);
    lv_obj_set_align(ui_Home_ImageBattery, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Home_ImageBattery, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Home_ImageBattery, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Home_ContainerInfo = lv_obj_create(ui_Home);
    lv_obj_remove_style_all(ui_Home_ContainerInfo);
    lv_obj_set_width(ui_Home_ContainerInfo, 212);
    lv_obj_set_height(ui_Home_ContainerInfo, 41);
    lv_obj_set_x(ui_Home_ContainerInfo, 0);
    lv_obj_set_y(ui_Home_ContainerInfo, -10);
    lv_obj_set_align(ui_Home_ContainerInfo, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Home_ContainerInfo, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Home_LabelTemp = lv_label_create(ui_Home_ContainerInfo);
    lv_obj_set_width(ui_Home_LabelTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Home_LabelTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Home_LabelTemp, -29);
    lv_obj_set_y(ui_Home_LabelTemp, 11);
    lv_obj_set_align(ui_Home_LabelTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Home_LabelTemp, "25/15°C");
    lv_obj_set_style_text_color(ui_Home_LabelTemp, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Home_LabelTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Home_LabelWeather = lv_label_create(ui_Home_ContainerInfo);
    lv_obj_set_width(ui_Home_LabelWeather, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Home_LabelWeather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Home_LabelWeather, -40);
    lv_obj_set_y(ui_Home_LabelWeather, -9);
    lv_obj_set_align(ui_Home_LabelWeather, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Home_LabelWeather, "Sun");
    lv_obj_set_style_text_color(ui_Home_LabelWeather, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Home_LabelWeather, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Home_ImageWeather = lv_image_create(ui_Home_ContainerInfo);
    lv_image_set_src(ui_Home_ImageWeather, &ui_img_weather_sunny_png);
    lv_obj_set_width(ui_Home_ImageWeather, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Home_ImageWeather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Home_ImageWeather, -80);
    lv_obj_set_y(ui_Home_ImageWeather, 0);
    lv_obj_set_align(ui_Home_ImageWeather, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Home_ImageWeather, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Home_ImageWeather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Home_LabelHeartbeat = lv_label_create(ui_Home_ContainerInfo);
    lv_obj_set_width(ui_Home_LabelHeartbeat, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Home_LabelHeartbeat, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Home_LabelHeartbeat, 77);
    lv_obj_set_y(ui_Home_LabelHeartbeat, 0);
    lv_obj_set_align(ui_Home_LabelHeartbeat, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Home_LabelHeartbeat, "75 BPM");
    lv_obj_set_style_text_color(ui_Home_LabelHeartbeat, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Home_LabelHeartbeat, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Home_ImageHeartbeat = lv_image_create(ui_Home_ContainerInfo);
    lv_image_set_src(ui_Home_ImageHeartbeat, &ui_img_heartbeat_png);
    lv_obj_set_width(ui_Home_ImageHeartbeat, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Home_ImageHeartbeat, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Home_ImageHeartbeat, 28);
    lv_obj_set_y(ui_Home_ImageHeartbeat, 0);
    lv_obj_set_align(ui_Home_ImageHeartbeat, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Home_ImageHeartbeat, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Home_ImageHeartbeat, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Home_PanelInfo = lv_obj_create(ui_Home);
    lv_obj_set_width(ui_Home_PanelInfo, 180);
    lv_obj_set_height(ui_Home_PanelInfo, 80);
    lv_obj_set_x(ui_Home_PanelInfo, 0);
    lv_obj_set_y(ui_Home_PanelInfo, 65);
    lv_obj_set_align(ui_Home_PanelInfo, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Home_PanelInfo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Home_PanelInfo, lv_color_hex(0x636D87), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Home_PanelInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Home_LabelStep = lv_label_create(ui_Home_PanelInfo);
    lv_obj_set_width(ui_Home_LabelStep, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Home_LabelStep, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Home_LabelStep, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Home_LabelStep, "Today's step: 3456");

    ui_Home_Arc1 = lv_arc_create(ui_Home);
    lv_obj_set_width(ui_Home_Arc1, 6);
    lv_obj_set_height(ui_Home_Arc1, 6);
    lv_obj_set_x(ui_Home_Arc1, -30);
    lv_obj_set_y(ui_Home_Arc1, -70);
    lv_obj_set_align(ui_Home_Arc1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Home_Arc1, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_Home_Arc1, 0);
    lv_arc_set_bg_angles(ui_Home_Arc1, 0, 360);

    lv_obj_set_style_opa(ui_Home_Arc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Home_Arc2 = lv_arc_create(ui_Home);
    lv_obj_set_width(ui_Home_Arc2, 6);
    lv_obj_set_height(ui_Home_Arc2, 6);
    lv_obj_set_x(ui_Home_Arc2, -30);
    lv_obj_set_y(ui_Home_Arc2, -50);
    lv_obj_set_align(ui_Home_Arc2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Home_Arc2, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_Home_Arc2, 0);
    lv_arc_set_bg_angles(ui_Home_Arc2, 0, 360);

    lv_obj_set_style_opa(ui_Home_Arc2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Home_PanelInfo, ui_event_Home_PanelInfo, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Home, ui_event_Home, LV_EVENT_ALL, NULL);

}
