// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: SmartBand

#include "../ui.h"

void ui_SettingsWristOn_screen_init(void)
{
    ui_SettingsWristOn = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SettingsWristOn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingsWristOn, lv_color_hex(0x393C41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingsWristOn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsWristOn_ImageWristOn = lv_image_create(ui_SettingsWristOn);
    lv_image_set_src(ui_SettingsWristOn_ImageWristOn, &ui_img_wrist_on_png);
    lv_obj_set_width(ui_SettingsWristOn_ImageWristOn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsWristOn_ImageWristOn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingsWristOn_ImageWristOn, 0);
    lv_obj_set_y(ui_SettingsWristOn_ImageWristOn, -75);
    lv_obj_set_align(ui_SettingsWristOn_ImageWristOn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingsWristOn_ImageWristOn, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_SettingsWristOn_ImageWristOn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingsWristOn_SwitchWristOn = lv_switch_create(ui_SettingsWristOn);
    lv_obj_set_width(ui_SettingsWristOn_SwitchWristOn, 60);
    lv_obj_set_height(ui_SettingsWristOn_SwitchWristOn, 30);
    lv_obj_set_align(ui_SettingsWristOn_SwitchWristOn, LV_ALIGN_CENTER);

    ui_SettingsWristOn_LabelWristOn = lv_label_create(ui_SettingsWristOn);
    lv_obj_set_width(ui_SettingsWristOn_LabelWristOn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsWristOn_LabelWristOn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingsWristOn_LabelWristOn, 0);
    lv_obj_set_y(ui_SettingsWristOn_LabelWristOn, -40);
    lv_obj_set_align(ui_SettingsWristOn_LabelWristOn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingsWristOn_LabelWristOn, "Wrist On");
    lv_obj_set_style_text_color(ui_SettingsWristOn_LabelWristOn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingsWristOn_LabelWristOn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SettingsWristOn_LabelWristOn, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsWristOn_LabelWristOnHint = lv_label_create(ui_SettingsWristOn);
    lv_obj_set_width(ui_SettingsWristOn_LabelWristOnHint, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsWristOn_LabelWristOnHint, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingsWristOn_LabelWristOnHint, 0);
    lv_obj_set_y(ui_SettingsWristOn_LabelWristOnHint, 60);
    lv_obj_set_align(ui_SettingsWristOn_LabelWristOnHint, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingsWristOn_LabelWristOnHint,
                      "When enabled, the\nscreen lights up when\nyou raise your wrist,\nno button needed.");
    lv_obj_set_style_text_color(ui_SettingsWristOn_LabelWristOnHint, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingsWristOn_LabelWristOnHint, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SettingsWristOn_LabelWristOnHint, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SettingsWristOn, ui_event_SettingsWristOn, LV_EVENT_ALL, NULL);

}
