// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: SmartBand

#include "../ui.h"

void ui_SettingsDebug_screen_init(void)
{
    ui_SettingsDebug = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SettingsDebug, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingsDebug, lv_color_hex(0x393C41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingsDebug, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsDebug_Keyboard2 = lv_keyboard_create(ui_SettingsDebug);
    lv_obj_set_width(ui_SettingsDebug_Keyboard2, 240);
    lv_obj_set_height(ui_SettingsDebug_Keyboard2, 120);
    lv_obj_set_x(ui_SettingsDebug_Keyboard2, 0);
    lv_obj_set_y(ui_SettingsDebug_Keyboard2, 80);
    lv_obj_set_align(ui_SettingsDebug_Keyboard2, LV_ALIGN_CENTER);

    ui_SettingsDebug_TextArea1 = lv_textarea_create(ui_SettingsDebug);
    lv_obj_set_width(ui_SettingsDebug_TextArea1, 150);
    lv_obj_set_height(ui_SettingsDebug_TextArea1, 50);
    lv_obj_set_x(ui_SettingsDebug_TextArea1, 20);
    lv_obj_set_y(ui_SettingsDebug_TextArea1, -80);
    lv_obj_set_align(ui_SettingsDebug_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_SettingsDebug_TextArea1, "Placeholder...");

    ui_SettingsDebug_TextArea2 = lv_textarea_create(ui_SettingsDebug);
    lv_obj_set_width(ui_SettingsDebug_TextArea2, 150);
    lv_obj_set_height(ui_SettingsDebug_TextArea2, 50);
    lv_obj_set_x(ui_SettingsDebug_TextArea2, 20);
    lv_obj_set_y(ui_SettingsDebug_TextArea2, -20);
    lv_obj_set_align(ui_SettingsDebug_TextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_SettingsDebug_TextArea2, "Placeholder...");

    ui_SettingsDebug_Label12 = lv_label_create(ui_SettingsDebug);
    lv_obj_set_width(ui_SettingsDebug_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsDebug_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingsDebug_Label12, -80);
    lv_obj_set_y(ui_SettingsDebug_Label12, -20);
    lv_obj_set_align(ui_SettingsDebug_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingsDebug_Label12, "TX");
    lv_obj_set_style_text_color(ui_SettingsDebug_Label12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingsDebug_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SettingsDebug_Label12, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsDebug_Label13 = lv_label_create(ui_SettingsDebug);
    lv_obj_set_width(ui_SettingsDebug_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsDebug_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingsDebug_Label13, -80);
    lv_obj_set_y(ui_SettingsDebug_Label13, -80);
    lv_obj_set_align(ui_SettingsDebug_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingsDebug_Label13, "RX");
    lv_obj_set_style_text_color(ui_SettingsDebug_Label13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingsDebug_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SettingsDebug_Label13, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_keyboard_set_textarea(ui_SettingsDebug_Keyboard2, ui_SettingsDebug_TextArea2);
    lv_obj_add_event_cb(ui_SettingsDebug, ui_event_SettingsDebug, LV_EVENT_ALL, NULL);

}
