// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: SmartBand

#include "../ui.h"

void ui_SettingsLockTime_screen_init(void)
{
    ui_SettingsLockTime = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SettingsLockTime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingsLockTime, lv_color_hex(0x393C41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingsLockTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsLockTime_ImageLockTime = lv_image_create(ui_SettingsLockTime);
    lv_image_set_src(ui_SettingsLockTime_ImageLockTime, &ui_img_turn_off_time_png);
    lv_obj_set_width(ui_SettingsLockTime_ImageLockTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsLockTime_ImageLockTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingsLockTime_ImageLockTime, 0);
    lv_obj_set_y(ui_SettingsLockTime_ImageLockTime, -75);
    lv_obj_set_align(ui_SettingsLockTime_ImageLockTime, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingsLockTime_ImageLockTime, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_SettingsLockTime_ImageLockTime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingsLockTime_LabelLockTime = lv_label_create(ui_SettingsLockTime);
    lv_obj_set_width(ui_SettingsLockTime_LabelLockTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsLockTime_LabelLockTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingsLockTime_LabelLockTime, 0);
    lv_obj_set_y(ui_SettingsLockTime_LabelLockTime, -40);
    lv_obj_set_align(ui_SettingsLockTime_LabelLockTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingsLockTime_LabelLockTime, "Lock Time");
    lv_obj_set_style_text_color(ui_SettingsLockTime_LabelLockTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingsLockTime_LabelLockTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SettingsLockTime_LabelLockTime, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsLockTime_LabelLockTimeHint = lv_label_create(ui_SettingsLockTime);
    lv_obj_set_width(ui_SettingsLockTime_LabelLockTimeHint, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsLockTime_LabelLockTimeHint, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingsLockTime_LabelLockTimeHint, 0);
    lv_obj_set_y(ui_SettingsLockTime_LabelLockTimeHint, 60);
    lv_obj_set_align(ui_SettingsLockTime_LabelLockTimeHint, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingsLockTime_LabelLockTimeHint,
                      "Set screen timeout\nafter inactivity to save\ndevice's power");
    lv_obj_set_style_text_color(ui_SettingsLockTime_LabelLockTimeHint, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingsLockTime_LabelLockTimeHint, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SettingsLockTime_LabelLockTimeHint, LV_TEXT_ALIGN_CENTER,
                                LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsLockTime_Dropdown1 = lv_dropdown_create(ui_SettingsLockTime);
    lv_dropdown_set_options(ui_SettingsLockTime_Dropdown1, "3s\n5s\n10s");
    lv_obj_set_width(ui_SettingsLockTime_Dropdown1, 100);
    lv_obj_set_height(ui_SettingsLockTime_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingsLockTime_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingsLockTime_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_add_event_cb(ui_SettingsLockTime, ui_event_SettingsLockTime, LV_EVENT_ALL, NULL);

}
