// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: SmartBand

#include "../ui.h"

void ui_SettingsAbout_screen_init(void)
{
    ui_SettingsAbout = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SettingsAbout, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingsAbout, lv_color_hex(0x393C41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingsAbout, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsAbout_ImageAuthor = lv_image_create(ui_SettingsAbout);
    lv_image_set_src(ui_SettingsAbout_ImageAuthor, &ui_img_author_png);
    lv_obj_set_width(ui_SettingsAbout_ImageAuthor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsAbout_ImageAuthor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingsAbout_ImageAuthor, 0);
    lv_obj_set_y(ui_SettingsAbout_ImageAuthor, -30);
    lv_obj_set_align(ui_SettingsAbout_ImageAuthor, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingsAbout_ImageAuthor, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_SettingsAbout_ImageAuthor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingsAbout_LabelAuthor = lv_label_create(ui_SettingsAbout);
    lv_obj_set_width(ui_SettingsAbout_LabelAuthor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsAbout_LabelAuthor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingsAbout_LabelAuthor, 0);
    lv_obj_set_y(ui_SettingsAbout_LabelAuthor, 30);
    lv_obj_set_align(ui_SettingsAbout_LabelAuthor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingsAbout_LabelAuthor, "Github@Marisa9961");
    lv_obj_set_style_text_color(ui_SettingsAbout_LabelAuthor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingsAbout_LabelAuthor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SettingsAbout_LabelAuthor, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SettingsAbout, ui_event_SettingsAbout, LV_EVENT_ALL, NULL);

}
