// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: SmartBand

#include "../ui.h"

void ui_Thermometer_screen_init(void)
{
    ui_Thermometer = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Thermometer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Thermometer, lv_color_hex(0x393C41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Thermometer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Thermometer_HeartBeatTitle1 = lv_label_create(ui_Thermometer);
    lv_obj_set_width(ui_Thermometer_HeartBeatTitle1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Thermometer_HeartBeatTitle1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Thermometer_HeartBeatTitle1, 0);
    lv_obj_set_y(ui_Thermometer_HeartBeatTitle1, -90);
    lv_obj_set_align(ui_Thermometer_HeartBeatTitle1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Thermometer_HeartBeatTitle1, "temperature & humidity");
    lv_obj_set_style_text_color(ui_Thermometer_HeartBeatTitle1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Thermometer_HeartBeatTitle1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Thermometer_HeartBeatTitle1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Thermometer_HeartBeatImage1 = lv_image_create(ui_Thermometer);
    lv_image_set_src(ui_Thermometer_HeartBeatImage1, &ui_img_thermometer_png);
    lv_obj_set_width(ui_Thermometer_HeartBeatImage1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Thermometer_HeartBeatImage1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Thermometer_HeartBeatImage1, -50);
    lv_obj_set_y(ui_Thermometer_HeartBeatImage1, -40);
    lv_obj_set_align(ui_Thermometer_HeartBeatImage1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Thermometer_HeartBeatImage1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Thermometer_HeartBeatImage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Thermometer_Image3 = lv_image_create(ui_Thermometer);
    lv_image_set_src(ui_Thermometer_Image3, &ui_img_humi_png);
    lv_obj_set_width(ui_Thermometer_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Thermometer_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Thermometer_Image3, -50);
    lv_obj_set_y(ui_Thermometer_Image3, 10);
    lv_obj_set_align(ui_Thermometer_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Thermometer_Image3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Thermometer_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Thermometer_Label2 = lv_label_create(ui_Thermometer);
    lv_obj_set_width(ui_Thermometer_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Thermometer_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Thermometer_Label2, 20);
    lv_obj_set_y(ui_Thermometer_Label2, -40);
    lv_obj_set_align(ui_Thermometer_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Thermometer_Label2, " 28 °C");
    lv_obj_set_style_text_color(ui_Thermometer_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Thermometer_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Thermometer_Label2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Thermometer_Label3 = lv_label_create(ui_Thermometer);
    lv_obj_set_width(ui_Thermometer_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Thermometer_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Thermometer_Label3, 20);
    lv_obj_set_y(ui_Thermometer_Label3, 10);
    lv_obj_set_align(ui_Thermometer_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Thermometer_Label3, "90 %");
    lv_obj_set_style_text_color(ui_Thermometer_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Thermometer_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Thermometer_Label3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Thermometer_Button3 = lv_button_create(ui_Thermometer);
    lv_obj_set_width(ui_Thermometer_Button3, 150);
    lv_obj_set_height(ui_Thermometer_Button3, 50);
    lv_obj_set_x(ui_Thermometer_Button3, 0);
    lv_obj_set_y(ui_Thermometer_Button3, 80);
    lv_obj_set_align(ui_Thermometer_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Thermometer_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Thermometer_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Thermometer_Button3, lv_color_hex(0x83858B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Thermometer_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Thermometer_Image4 = lv_image_create(ui_Thermometer_Button3);
    lv_image_set_src(ui_Thermometer_Image4, &ui_img_restart_png);
    lv_obj_set_width(ui_Thermometer_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Thermometer_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Thermometer_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Thermometer_Image4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Thermometer_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Thermometer, ui_event_Thermometer, LV_EVENT_ALL, NULL);

}
