// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: SmartBand

#include "../ui.h"

void ui_Timer_screen_init(void)
{
    ui_Timer = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Timer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Timer, lv_color_hex(0x393C41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Timer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Timer_Arc1 = lv_arc_create(ui_Timer);
    lv_obj_set_width(ui_Timer_Arc1, 150);
    lv_obj_set_height(ui_Timer_Arc1, 150);
    lv_obj_set_x(ui_Timer_Arc1, 0);
    lv_obj_set_y(ui_Timer_Arc1, -30);
    lv_obj_set_align(ui_Timer_Arc1, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Timer_Arc1, 0);
    lv_arc_set_bg_angles(ui_Timer_Arc1, 0, 360);
    lv_arc_set_rotation(ui_Timer_Arc1, -90);

    lv_obj_set_style_arc_color(ui_Timer_Arc1, lv_color_hex(0x00AEB4), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Timer_Arc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Timer_Arc1, lv_color_hex(0x83858B), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Timer_Arc1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Timer_Label1 = lv_label_create(ui_Timer);
    lv_obj_set_width(ui_Timer_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Timer_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Timer_Label1, 0);
    lv_obj_set_y(ui_Timer_Label1, -30);
    lv_obj_set_align(ui_Timer_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Timer_Label1, "00:00:00");
    lv_obj_set_style_text_color(ui_Timer_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Timer_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Timer_Label1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Timer_Button1 = lv_button_create(ui_Timer);
    lv_obj_set_width(ui_Timer_Button1, 50);
    lv_obj_set_height(ui_Timer_Button1, 50);
    lv_obj_set_x(ui_Timer_Button1, -80);
    lv_obj_set_y(ui_Timer_Button1, 90);
    lv_obj_set_align(ui_Timer_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Timer_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Timer_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Timer_Button1, lv_color_hex(0x83858B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Timer_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Timer_Image1 = lv_image_create(ui_Timer_Button1);
    lv_image_set_src(ui_Timer_Image1, &ui_img_start_png);
    lv_obj_set_width(ui_Timer_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Timer_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Timer_Image1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Timer_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Timer_Button2 = lv_button_create(ui_Timer);
    lv_obj_set_width(ui_Timer_Button2, 50);
    lv_obj_set_height(ui_Timer_Button2, 50);
    lv_obj_set_x(ui_Timer_Button2, 80);
    lv_obj_set_y(ui_Timer_Button2, 90);
    lv_obj_set_align(ui_Timer_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Timer_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Timer_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Timer_Button2, lv_color_hex(0x83858B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Timer_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Timer_Image2 = lv_image_create(ui_Timer_Button2);
    lv_image_set_src(ui_Timer_Image2, &ui_img_restart_png);
    lv_obj_set_width(ui_Timer_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Timer_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Timer_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Timer_Image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Timer_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Timer, ui_event_Timer, LV_EVENT_ALL, NULL);

}
